name: Deployment Workflow
on:
    push: 
        branches:
            - master
jobs:
    preparation:
        runs-on: ubuntu-latest
        steps:
            - name: preparation
              run:  echo "preparing to deploy"
            - name: checks out the repository
              uses: actions/checkout@v4
            - name: "Logs into Docker Hub"
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: "Build our code"
              env:
                IMAGE_NAME: automated_runner
                VERSION: 1
                USERNAME: monyslim
              run: |
                  docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
                  docker push $USERNAME/$IMAGE_NAME:$VERSION